function [egoState, tracks] = createPhase4Demo(config)
%CREATEPHASE4DEMO Deterministic struct-only Phase 4 harness.
%   This does not use drivingScenario or Automated Driving Toolbox.

    if nargin < 1 || isempty(config)
        cfg = feval('config');
    else
        cfg = config;
    end
    cfg.tracking.preferTrackingKF = false;
    egoState = struct('Position', [0 0], 'Velocity', [8 0]);
    actorData = { ...
        201, 'car',        [25  2], [ 5  0]; ...
        202, 'pedestrian', [15 -4], [ 0  1]; ...
        203, 'motorcycle', [30  4], [ 3 -1]; ...
        204, 'cattle',     [40  3], [-1  0]};
    tracks = struct([]);
    for index = 1:size(actorData, 1)
        detection = struct('ID', actorData{index, 1}, ...
            'Position', [actorData{index, 3}, 0], ...
            'Velocity', [actorData{index, 4}, 0], ...
            'PerceivedClass', actorData{index, 2}, ...
            'TrueClass', actorData{index, 2}, ...
            'PositionStd', [0.4 0.4 0.1], ...
            'VelocityStd', [0.5 0.5 0.1], ...
            'IsDetected', true, 'Confidence', 0.9);
        tracks(end + 1) = initializeTracker(detection, cfg.sim.dt, cfg, 0); %#ok<SAGROW>
    end
end
