function plannerData = createPlanner(riskMap, config)
%CREATEPLANNER Create a vehicle-aware Hybrid A* baseline from Phase 4 output.
%   The temporal risk grid is intentionally not supplied to Hybrid A*. A copy
%   of riskMap.staticConservativeMap is inflated by the configured ego-footprint
%   envelope before it is assigned to validatorOccupancyMap.

    cfg = planningConfig(config);
    conservativeMap = conservativeMapOf(riskMap);
    validationMap = copy(conservativeMap);
    inflationRadius = hypot(cfg.vehicle.length / 2, cfg.vehicle.width / 2) + ...
        cfg.vehicle.validationSafetyMargin;
    inflate(validationMap, inflationRadius);

    stateSpace = stateSpaceSE2;
    stateSpace.StateBounds = [validationMap.XWorldLimits; ...
        validationMap.YWorldLimits; [-pi pi]];
    validator = validatorOccupancyMap(stateSpace, Map=validationMap);
    validator.ValidationDistance = cfg.planning.validationDistance;
    planner = plannerHybridAStar(validator, ...
        MinTurningRadius=cfg.planning.minTurningRadius, ...
        MotionPrimitiveLength=cfg.planning.motionPrimitiveLength, ...
        NumMotionPrimitives=cfg.planning.numMotionPrimitives, ...
        MotionDirection=cfg.planning.motionDirection, ...
        ForwardCost=cfg.planning.forwardCost, ...
        ReverseCost=cfg.planning.reverseCost, ...
        DirectionSwitchingCost=cfg.planning.directionSwitchingCost, ...
        AnalyticExpansionInterval=cfg.planning.analyticExpansionInterval, ...
        InterpolationDistance=cfg.planning.interpolationDistance, ...
        MaxNumNodes=cfg.planning.maxNumNodes, ...
        MaxNumPathStates=cfg.planning.maxNumPathStates);

    plannerData = struct('Planner', planner, 'Validator', validator, ...
        'StateSpace', stateSpace, 'BaseConservativeMap', conservativeMap, ...
        'ValidationMap', validationMap, 'VehicleLength', cfg.vehicle.length, ...
        'VehicleWidth', cfg.vehicle.width, ...
        'VehicleInflationRadius', inflationRadius, ...
        'CoordinateConvention', '[x,y,theta] world pose; x longitudinal, y lateral');
end

function map = conservativeMapOf(riskMap)
    if isstruct(riskMap) && isfield(riskMap, 'staticConservativeMap')
        map = riskMap.staticConservativeMap;
    elseif isa(riskMap, 'binaryOccupancyMap')
        map = riskMap;
    else
        error('createPlanner:InvalidOccupancyInput', ...
            'Supply a Phase 4 riskMap or binaryOccupancyMap conservative map.');
    end
    if ~isa(map, 'binaryOccupancyMap')
        error('createPlanner:InvalidConservativeMap', ...
            'The conservative occupancy representation must be binaryOccupancyMap.');
    end
end

function cfg = planningConfig(config)
    cfg = config;
    if ~isfield(cfg, 'planning') || ~isfield(cfg, 'vehicle')
        error('createPlanner:MissingConfiguration', ...
            'Full configuration must contain planning and vehicle sections.');
    end
    required = {'minTurningRadius', 'motionPrimitiveLength', ...
        'numMotionPrimitives', 'motionDirection', 'forwardCost', 'reverseCost', ...
        'directionSwitchingCost', 'analyticExpansionInterval', ...
        'interpolationDistance', 'maxNumNodes', 'maxNumPathStates', ...
        'validationDistance'};
    for index = 1:numel(required)
        if ~isfield(cfg.planning, required{index})
            error('createPlanner:MissingConfiguration', ...
                'Missing planning configuration field: %s.', required{index});
        end
    end
end
