function scenarios = getPhase8Scenarios(cfg)
%GETPHASE8SCENARIOS Return the five required scenarios in registry order.

    scenarios = {createVillageRoadScenario(cfg), ...
        createUrbanIntersectionScenario(cfg), ...
        createHighwayMergeScenario(cfg), ...
        createDenseMarketScenario(cfg), ...
        createCattleCrossingScenario(cfg)};
end
