function actor = makePhase8Actor(id, actorClass, position, velocity, dimensions, name)
%MAKEPHASE8ACTOR Create finite deterministic truth using the common schema.

    actor = struct('ID', id, 'TrueClass', actorClass, 'ClassID', NaN, ...
        'Class', actorClass, 'ActorClass', actorClass, 'Name', name, ...
        'Position', [position(1:2) 0], 'Velocity', [velocity(1:2) 0], ...
        'Yaw', atan2(velocity(2), velocity(1)), 'Orientation', [], ...
        'Dimensions', [dimensions(1:2) 1.5]);
end
