function scenario = makePhase8Scenario(name, description, ego, goal, actors, ...
        maxSimulationTime, expectedBehavior, seed, cfg)
%MAKEPHASE8SCENARIO Package a runClosedLoopSimulation-compatible scenario.

    cfg = configurePhase8Scenario(cfg, maxSimulationTime, seed);
    scenario = struct('name', name, 'description', description, ...
        'egoInitialState', ego, 'egoState', ego, 'goalPose', goal, ...
        'actors', actors, 'maxSimulationTime', maxSimulationTime, ...
        'expectedBehavior', expectedBehavior, 'seed', seed, 'config', cfg);
end
