function overlay = buildRoadRunnerDiagnosticOverlay(frame, activePath)
%BUILDROADRUNNERDIAGNOSTICOVERLAY Prepare synchronized MATLAB overlay data.

    if nargin<2 || isempty(activePath), activePath=struct('states',zeros(0,3)); end
    overlay=struct('simulationTime',fieldOr(frame,'time',NaN), ...
        'actors',fieldOr(frame,'actorTruth',struct([])), ...
        'predictedTrajectories',repmat(struct('ActorID',NaN,'Position',zeros(0,2)),0,1), ...
        'safetyEnvelopes',repmat(struct('ActorID',NaN,'baseExtent',[NaN NaN], ...
            'adaptiveExtent',[NaN NaN]),0,1), ...
        'activeEgoPath',zeros(0,3),'acargState',string(fieldOr(frame,'acargState','')));
    tracks=fieldOr(frame,'tracks',struct([]));
    for i=1:numel(tracks)
        if isfield(tracks(i),'Prediction') && isfield(tracks(i).Prediction,'Position')
            overlay.predictedTrajectories(end+1,1)=struct( ...
                'ActorID',tracks(i).ActorID,'Position',tracks(i).Prediction.Position);
        end
    end
    risks=fieldOr(frame,'actorRiskDetails',struct([]));
    for i=1:numel(risks)
        overlay.safetyEnvelopes(end+1,1)=struct('ActorID',risks(i).ActorID, ...
            'baseExtent',[fieldOr(risks(i),'baseSafetyExtentX',NaN) ...
                fieldOr(risks(i),'baseSafetyExtentY',NaN)], ...
            'adaptiveExtent',[fieldOr(risks(i),'effectiveSafetyExtentX',NaN) ...
                fieldOr(risks(i),'effectiveSafetyExtentY',NaN)]);
    end
    if isfield(activePath,'states'), overlay.activeEgoPath=activePath.states; end
end
function value=fieldOr(s,name,fallback)
if isstruct(s)&&isfield(s,name), value=s.(name); else, value=fallback; end
end
