function adapter = createRoadRunnerAdapter(cfg, manifest)
%CREATEROADRUNNERADAPTER Build simulator boundary with no runtime side effect.

    if nargin < 1 || isempty(cfg), cfg = config(); end
    if nargin < 2 || isempty(manifest), manifest = loadRoadRunnerManifest('village', cfg); end
    adapter = struct('name', "SIH RoadRunner Adapter", ...
        'bridgeMode', string(cfg.roadrunner.bridgeMode), ...
        'controlStep', cfg.roadrunner.controlStep, ...
        'capability', isRoadRunnerAvailable(cfg), ...
        'manifest', manifest, 'runtimeAPICalls', 0, ...
        'roadRunnerToCanonicalActors', ...
            @(states) roadRunnerToCanonicalActors(states, manifest), ...
        'canonicalEgoToRoadRunner', ...
            @(ego) canonicalEgoToRoadRunner(ego, manifest), ...
        'canonicalPoseToRoadRunner', ...
            @(pose) canonicalPoseToRoadRunner(pose, manifest), ...
        'roadRunnerPoseToCanonical', ...
            @(pose) roadRunnerPoseToCanonical(pose, manifest), ...
        'validateTime', ...
            @(matlabTime,rrTime,frame) validateTimeSynchronization( ...
                matlabTime,rrTime,frame,cfg));
end
