function metrics = emptyRoadRunnerMetrics()
%EMPTYROADRUNNERMETRICS Standard Phase 10 integration metric schema.
metrics=struct('statePositionError',NaN,'yawError',NaN,'speedError',NaN, ...
    'timeSynchronizationError',NaN,'actorCountMismatch',NaN, ...
    'ActorIDMismatchCount',NaN,'classMismatchCount',NaN, ...
    'framesExchanged',0,'integrationRuntime',0,'roadRunnerConnected',false, ...
    'scenarioOpened',false,'simulationCreated',false);
end
