function status = validateTimeSynchronization(matlabTime, roadRunnerTime, frameIndex, cfg)
%VALIDATETIMESYNCHRONIZATION Compare simulation clocks, never wall clock.

    if nargin < 4 || isempty(cfg), cfg = config(); end
    errorValue = abs(double(matlabTime)-double(roadRunnerTime));
    expectedMatlabTime = double(frameIndex) * cfg.roadrunner.controlStep;
    frameError = abs(double(matlabTime)-expectedMatlabTime);
    status = struct('synchronized', errorValue <= cfg.roadrunner.maxTimeDrift && ...
        frameError <= cfg.roadrunner.maxTimeDrift, ...
        'timeSynchronizationError', errorValue, 'frameTimeError', frameError, ...
        'matlabTime', double(matlabTime), 'roadRunnerTime', double(roadRunnerTime), ...
        'frameIndex', double(frameIndex), 'controlStep', cfg.roadrunner.controlStep, ...
        'tolerance', cfg.roadrunner.maxTimeDrift);
end
