function catalog=scenarioVideoCatalog()
%SCENARIOVIDEOCATALOG Required coverage, canonical source names and file names.
names=["Unmarked Village Road";"Unsignalized Urban Intersection";"Highway Slow-Vehicle Merge"; ...
    "Dense Mixed-Traffic Market";"Sudden Cattle Crossing";"Confidence Drop"; ...
    "Temporary Detection Loss";"Sudden Direction Reversal";"Multiple Simultaneous Risks"; ...
    "Temporary Path Obstruction";"Replan Failure Recovery";"Conservative Stop Recovery";"Rapid Risk Fluctuation"];
stems=["01_village_road";"02_urban_intersection";"03_highway_merge";"04_dense_market"; ...
    "05_cattle_crossing";"06_confidence_drop";"07_detection_loss";"08_direction_reversal"; ...
    "09_multiple_risks";"10_temporary_obstruction";"11_replan_failure_recovery"; ...
    "12_stop_recovery";"13_rapid_risk_fluctuation"];
concept=["Mixed traffic and adaptive risk";"Safe planning failure guard";"Prediction-aware merge"; ...
    "Dense traffic and safe progress";"Crossing vulnerability and adaptive envelopes"; ...
    "Confidence and uncertainty awareness";"Missed detections and track uncertainty"; ...
    "Direction-sensitive CPA";"Scene-wide dominant risk selection";"Temporary path obstruction"; ...
    "Failed planning, braking and later recovery";"STOP hysteresis and physical braking";"Hysteresis under changing risk"];
catalog=table((1:13).',names,[repmat(8,5,1);repmat(9,8,1)],stems,concept, ...
    'VariableNames',{'VideoID','Scenario','Phase','FileStem','Concept'});
end
