function evaluation = evaluateIDDDetector(detector,data,cfg)
%EVALUATEIDDDETECTOR Genuine official validation only, no fabricated metrics.
assert(isa(detector,'yoloxObjectDetector'),'IDD:Detector','Expected MATLAB YOLOX detector.');
[~,images,truth]=buildIDDDetectionDatastore(data.val);
predictions=detect(detector,images,'Threshold',cfg.evaluationThreshold, ...
    'MiniBatchSize',cfg.batchSize,'ExecutionEnvironment',char(cfg.executionEnvironment));
metrics=evaluateObjectDetection(predictions,truth,cfg.iouThresholds);
[globalSummary,perClass]=summarize(metrics);
[recall,precision,scores]=precisionRecall(metrics);
evaluation=struct('status',"PASS",'split',"official validation", ...
    'imageCount',height(data.val),'scoreFloor',cfg.evaluationThreshold,'iouThresholds',cfg.iouThresholds, ...
    'metrics',metrics,'globalSummary',globalSummary,'perClass',perClass, ...
    'recall',{recall},'precision',{precision},'scores',{scores}, ...
    'confusionStatus',"Not computed; class-aware IoU precision/recall/AP reported", ...
    'validationImageFiles',data.val.imageFilename);
end
