function cfg = getIDDConfig(overrides)
%GETIDDCONFIG Isolated, opt-in image-perception configuration. No downloads.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
cfg=struct('enabled',false,'perceptionMode',"SIMULATED",'root',"",'variant',"IDD_DETECTION", ...
    'source',"https://idd.insaan.iiit.ac.in/dataset/download/", ...
    'annotationFormat',"VOC_XML",'annotationVersion',"UNVERIFIED", ...
    'labelField',"name",'classHierarchy',"raw XML object/name", ...
    'imageFolder',"JPEGImages",'annotationFolder',"Annotations", ...
    'trainList',"",'valList',"",'testList',"",'profile',"SMOKE", ...
    'model',"YOLOX",'pretrainedName',"nano-coco",'inputSize',[320 320 3], ...
    'batchSize',1,'maxEpochs',1,'initialLearnRate',1e-4,'optimizer',"sgdm", ...
    'executionEnvironment',"auto",'runTraining',false,'allowWeightDownload',false, ...
    'pretrainedDetectorFile',"",'detectorFile',"",'resumeFile',"", ...
    'targetLabels',strings(0,1),'includeDifficult',false, ...
    'trainLimit',16,'valLimit',8,'randomSeed',125,'maxSmokeSeconds',180, ...
    'minimumConversionFreeGB',2,'minimumTrainingFreeGB',5, ...
    'minimumFullTrainingFreeGB',10,'scoreThreshold',.25,'evaluationThreshold',.01, ...
    'iouThresholds',.5:.05:.95,'overlayCount',25, ...
    'augmentation',struct('flipProbability',0,'brightness',.08,'contrast',.1), ...
    'outputDir',string(fullfile(root,'results','idd')), ...
    'checkpointDir',"",'projectRoot',string(root));
if nargin<1,overrides=struct();end
if isfield(overrides,'idd'),overrides=overrides.idd;end
if isfield(overrides,'profile')
    switch upper(string(overrides.profile))
        case "SMOKE"
        case "DEVELOPMENT",cfg.trainLimit=512;cfg.valLimit=128;cfg.maxEpochs=20;cfg.batchSize=4;
        case "FULL",cfg.trainLimit=Inf;cfg.valLimit=Inf;cfg.maxEpochs=80;cfg.batchSize=8;cfg.inputSize=[640 640 3];
        otherwise,error('IDD:Profile','Choose SMOKE, DEVELOPMENT, or FULL.');
    end
end
fields=fieldnames(overrides);
for k=1:numel(fields)
    assert(isfield(cfg,fields{k}),'IDD:Config','Unknown IDD setting: %s',fields{k});
    cfg.(fields{k})=overrides.(fields{k});
end
cfg.profile=upper(string(cfg.profile));
assert(isscalar(cfg.batchSize)&&isfinite(cfg.batchSize)&&cfg.batchSize>=1&&cfg.batchSize==fix(cfg.batchSize)&&isscalar(cfg.maxEpochs)&&isfinite(cfg.maxEpochs)&&cfg.maxEpochs>=1&&cfg.maxEpochs==fix(cfg.maxEpochs),'IDD:Config','Invalid training size.');
assert(isequal(size(cfg.inputSize),[1 3])&&all(isfinite(cfg.inputSize)&cfg.inputSize>0&cfg.inputSize==fix(cfg.inputSize))&&cfg.inputSize(3)==3,'IDD:Config','InputSize must be integer [H W 3].');
assert(isscalar(cfg.trainLimit)&&isscalar(cfg.valLimit)&&all([cfg.trainLimit cfg.valLimit]>=1)&&all([cfg.trainLimit cfg.valLimit]==fix([cfg.trainLimit cfg.valLimit])),'IDD:Config','Split limits must be positive integers or Inf.');
assert(isscalar(cfg.initialLearnRate)&&isfinite(cfg.initialLearnRate)&&cfg.initialLearnRate>0&&isscalar(cfg.maxSmokeSeconds)&&isfinite(cfg.maxSmokeSeconds)&&cfg.maxSmokeSeconds>0,'IDD:Config','Learning rate and smoke time budget must be positive finite values.');
assert(all(isfinite([cfg.scoreThreshold cfg.evaluationThreshold cfg.iouThresholds]))&&all([cfg.scoreThreshold cfg.evaluationThreshold cfg.iouThresholds]>=0)&&all([cfg.scoreThreshold cfg.evaluationThreshold cfg.iouThresholds]<=1),'IDD:Config','Score and IoU thresholds must be in [0,1].');
assert(all(isfinite([cfg.augmentation.flipProbability cfg.augmentation.brightness cfg.augmentation.contrast]))&&all([cfg.augmentation.flipProbability cfg.augmentation.brightness cfg.augmentation.contrast]>=0)&&all([cfg.augmentation.flipProbability cfg.augmentation.brightness cfg.augmentation.contrast]<=1),'IDD:Config','Augmentation strengths must be in [0,1].');
if cfg.profile=="SMOKE",assert(cfg.maxEpochs<=2&&cfg.trainLimit<=32&&cfg.valLimit<=32,'IDD:SmokeBudget','SMOKE is limited to 32 images per split and two epochs.');end
if cfg.profile=="FULL",assert(isinf(cfg.trainLimit)&&isinf(cfg.valLimit),'IDD:FullSubset','FULL must use complete official train and validation splits.');end
end
