function text = summarizeIDDTraining(result)
%SUMMARIZEIDDTRAINING Keep architecture, data, training and evaluation distinct.
text=sprintf(['IDD INTEGRATION ARCHITECTURE: %s\nIDD DATASET PARSING: %s\n' ...
    'YOLOX SMOKE TRAINING: %s\nFULL IDD TRAINING: %s\nIDD VALIDATION: %s\n' ...
    'IDD -> CANONICAL DETECTIONS: %s (schema/semantic adapter; image-only is NOT metric-ready)\n' ...
    'YOLOX CAPABILITY: %s\n%s\n'],result.architecture.status,result.parsing, ...
    result.smokeTraining,result.fullTraining,result.validation,result.canonical, ...
    result.environment.status,result.message);
end
