function capability=validateIDDExecutionEnvironment(cfg)
%VALIDATEIDDEXECUTIONENVIRONMENT Explicit capability fields; no installation.
if nargin<1,cfg=getIDDExecutionConfig();end
r=validateIDDEnvironment(cfg);
capability=struct('YOLOXAvailable',~isempty(which('yoloxObjectDetector')), ...
    'TrainingFunctionAvailable',~isempty(which('trainYOLOXObjectDetector')), ...
    'DeepLearningAvailable',r.deepLearning,'ComputerVisionAvailable',r.computerVision, ...
    'ParallelComputingAvailable',any(string({r.toolboxes.Name})=="Parallel Computing Toolbox"), ...
    'GPUAvailable',r.gpuCount>0,'GPUName',r.gpuName, ...
    'ExecutionEnvironment',string(cfg.executionEnvironment),'details',r);
end
