function audit = validateIDDArchitecture(cfg)
%VALIDATEIDDARCHITECTURE Dataset-independent contracts, not a training success.
if nargin<1,cfg=getIDDConfig();end
required=["getIDDConfig","findIDDDataset","inspectIDDStructure","parseIDDAnnotations", ...
    "prepareIDDData","buildIDDDetectionDatastore","mapIDDClass","createIDDYOLOXDetector", ...
    "trainIDDYOLOX","resumeIDDYOLOXTraining","evaluateIDDDetector","runIDDInference", ...
    "iddDetectionToCanonical","createPerceptionSource","estimateActorStateFromVision", ...
    "loadIDDDetector","mainIDDPerceptionDemo"];
present=arrayfun(@(f) ~isempty(which(char(f))),required);
schemas=getPerceptionSchemas();
boundary=~any(ismember({'Position','Velocity'},schemas.ImageDetection.fields));
mapping=mapIDDClass("animal")=="animal"&&mapIDDClass("autorickshaw")=="auto"&&mapIDDClass("pushcart")=="unknown";
audit=struct('status',"COMPLETE",'requiredFunctions',required,'functionsPresent',present, ...
    'imageMetricBoundary',boundary,'classMappingContract',mapping,'schemas',schemas, ...
    'defaultMode',cfg.perceptionMode,'scope',"Dataset-independent implementation only; actual parser/training requires genuine data and YOLOX add-on");
if ~all(present)||~boundary||~mapping,audit.status="INCOMPLETE";end
end
