function ui = createDemoFigure(options)
%CREATEDEMOFIGURE One high-contrast window with stable axes positions.
f=figure('Name','ACARG | See - Assess - Respond','NumberTitle','off', ...
    'Color',[1 1 1],'Position',[40 40 1440 900],'Visible',options.visible, ...
    'MenuBar','none','ToolBar','none','Resize','off');
set(f,'DefaultAxesColor','w','DefaultAxesXColor',[.15 .2 .25], ...
    'DefaultAxesYColor',[.15 .2 .25],'DefaultTextColor',[.1 .15 .2], ...
    'DefaultTextInterpreter','none','DefaultLegendInterpreter','none', ...
    'DefaultAxesFontSize',11);
ui=struct('figure',f,'environment',axes(f,'Position',[.055 .36 .59 .55]), ...
    'panel',axes(f,'Position',[.69 .36 .29 .57]), ...
    'risk',axes(f,'Position',[.055 .095 .28 .18]), ...
    'speed',axes(f,'Position',[.385 .095 .28 .18]), ...
    'events',axes(f,'Position',[.70 .06 .28 .24]));
annotation(f,'textbox',[.055 .935 .88 .05],'String', ...
    'ACARG  |  See the conflict. Understand the response.', ...
    'EdgeColor','none','FontSize',20,'FontWeight','bold','Color',[.08 .16 .23]);
end
