function cfg = demoConfig()
%DEMOCONFIG Presentation settings, isolated from autonomy parameters.
cfg=struct('enabled',true,'mode','REPLAY','scenario','Cattle Crossing', ...
    'showPredictions',true,'showAdaptiveEnvelopes',true, ...
    'showRiskPlot',true,'showSpeedPlot',true,'showAdvancedExplanation',false, ...
    'showPerformance',false,'captureVideo',false,'exportScreenshots',false, ...
    'playbackSpeed',0.5,'holdFinalFrame',true,'visible','on', ...
    'animate',true,'frameRate',10,'outputRoot', ...
    fullfile(fileparts(fileparts(mfilename('fullpath'))),'results','phase12'));
end
