function audit = analyzeDenseMarketStop(cfg)
%ANALYZEDENSEMARKETSTOP Explain the Phase 8 STOP and verify the correction.

    if nargin < 1, cfg = config(); end
    [legacyDetail, legacyRow, sourceFile] = findLegacyDenseMarketResult();
    scenario = createDenseMarketScenario(cfg);
    requestedTimes = (10.6:0.2:12.2).';
    rows = cell(numel(requestedTimes), 1);
    log = legacyDetail.log;
    for k = 1:numel(requestedTimes)
        [~, index] = min(abs([log.time] - requestedTimes(k)));
        frame = log(index);
        [~, dominantIndex] = max([frame.actorRiskDetails.risk]);
        actorRisk = frame.actorRiskDetails(dominantIndex);
        actorIndex = find([scenario.actors.ID] == actorRisk.ActorID, 1);
        actorPosition = scenario.actors(actorIndex).Position(1:2) + ...
            scenario.actors(actorIndex).Velocity(1:2) * frame.time;
        actorVelocity = scenario.actors(actorIndex).Velocity(1:2);
        egoPosition = [frame.egoX frame.egoY];
        egoVelocity = frame.egoSpeed * [cos(frame.egoYaw) sin(frame.egoYaw)];
        cpa = computeTTC(actorPosition, actorVelocity, egoPosition, egoVelocity);
        positionTrace = actorRisk.uncertainty * ...
            scenario.config.governor.uncertainty.varianceScale;
        covariance = diag([positionTrace/2 positionTrace/2 0.04 0.04]);
        envelope = computeUncertaintyFootprint( ...
            [actorPosition actorVelocity].', covariance, ...
            actorRisk.perceivedClass, scenario.config);
        combinedScale = actorRisk.safetyScale * frame.safetyScale;
        previousState = frame.acargState;
        if index > 1, previousState = log(index - 1).acargState; end
        threshold = relevantThreshold(previousState, frame.acargState, ...
            scenario.config.governor.thresholds);
        rows{k} = struct('Time', frame.time, 'DominantActorID', actorRisk.ActorID, ...
            'ActorClass', string(actorRisk.perceivedClass), ...
            'EgoX', frame.egoX, 'EgoY', frame.egoY, ...
            'ActorX', actorPosition(1), 'ActorY', actorPosition(2), ...
            'PhysicalDistance', norm(actorPosition - egoPosition), ...
            'CPADistance', cpa.dCPA, 'CPATime', cpa.tCPA, ...
            'Confidence', actorRisk.confidence, 'Uncertainty', actorRisk.uncertainty, ...
            'UncertaintyContribution', 0.25 * actorRisk.uncertainty, ...
            'ConfidenceContribution', 0.25 * (1 - actorRisk.confidence), ...
            'DistanceContribution', 0.20 * actorRisk.distanceRisk, ...
            'CollisionContribution', 0.30 * actorRisk.collisionRisk, ...
            'RawActorRisk', actorRisk.rawRisk, 'FinalActorRisk', actorRisk.risk, ...
            'ActorScale', actorRisk.safetyScale, ...
            'StateSafetyScale', frame.safetyScale, ...
            'CombinedAdaptiveScale', combinedScale, ...
            'EffectiveSafetyExtentX', envelope.SemiAxes(1) * combinedScale, ...
            'EffectiveSafetyExtentY', envelope.SemiAxes(2) * combinedScale, ...
            'TotalRisk', frame.totalRisk, ...
            'PreviousState', string(previousState), ...
            'FinalState', string(frame.acargState), 'RelevantThreshold', threshold, ...
            'PathSafe', frame.pathSafe, 'ReplanRequested', frame.replanRequested, ...
            'PlannerInvoked', frame.plannerInvoked);
    end
    frameTable = struct2table(vertcat(rows{:}));
    stopIndex = find(strcmp({log.acargState}, 'CONSERVATIVE_STOP'), 1);
    afterStopRisk = [log(stopIndex:end).totalRisk];
    [acargReplans, unsafePathReplans] = classifyPlanEvents(legacyDetail.planEvents);
    transitionRow = frameTable(abs(frameTable.Time - 11.6) < 1e-9, :);
    postFixResult = runClosedLoopSimulation(scenario);
    audit = struct('classification', ...
        'C. Genuine implementation defect (time urgency overrode spatial evidence).', ...
        'legacySourceFile', sourceFile, 'legacySummary', legacyRow, ...
        'frameAudit', frameTable, 'transition', transitionRow, ...
        'stopEntryThreshold', scenario.config.governor.thresholds.conservativeEnter, ...
        'stopExitThreshold', scenario.config.governor.thresholds.conservativeExit, ...
        'minimumRiskAfterStop', min(afterStopRisk), ...
        'riskEverBelowStopExit', any(afterStopRisk <= ...
            scenario.config.governor.thresholds.conservativeExit), ...
        'dominantActorInsideImmediatePathHorizon', ...
            transitionRow.PhysicalDistance <= scenario.config.control.pathSafetyHorizon, ...
        'occupancyBlockedUsefulPaths', ~transitionRow.PathSafe, ...
        'acargAttributedPlanEvents', acargReplans, ...
        'unsafePathAttributedPlanEvents', unsafePathReplans, ...
        'defectCause', ['minimumPredictionTime=0 produced timeComponent=1 and ' ...
            'the previous max aggregation ignored large separation and zero CPA risk.'], ...
        'correction', ['time urgency now multiplies predicted-distance risk; ' ...
            'CPA, thresholds, weights, aggregation, and hysteresis are unchanged.'], ...
        'postFix', compactResult(postFixResult));
end

function [detail, row, source] = findLegacyDenseMarketResult()
    projectRoot = fileparts(fileparts(mfilename('fullpath')));
    files = dir(fullfile(projectRoot, 'results', 'phase8', 'phase8Benchmark_*.mat'));
    [~, order] = sort([files.datenum], 'descend');
    for fileIndex = order
        source = fullfile(files(fileIndex).folder, files(fileIndex).name);
        data = load(source, 'details', 'summaryTable');
        if ~isfield(data, 'details'), continue; end
        index = find(strcmp({data.details.scenarioName}, 'Dense Mixed-Traffic Market'), 1);
        if isempty(index), continue; end
        if any(strcmp({data.details(index).log.acargState}, 'CONSERVATIVE_STOP'))
            detail = data.details(index);
            row = data.summaryTable(index, :);
            return;
        end
    end
    error('analyzeDenseMarketStop:MissingLegacyRun', ...
        'No saved Phase 8 Dense Market STOP run was found.');
end

function threshold = relevantThreshold(previousState, finalState, thresholds)
    if strcmp(previousState, 'CAUTIOUS') && strcmp(finalState, 'CONSERVATIVE_STOP')
        threshold = thresholds.conservativeEnter;
    elseif strcmp(previousState, 'CONSERVATIVE_STOP')
        threshold = thresholds.conservativeExit;
    elseif strcmp(finalState, 'NORMAL')
        threshold = thresholds.cautiousExit;
    else
        threshold = thresholds.cautiousEnter;
    end
end

function [acargCount, unsafeCount] = classifyPlanEvents(events)
    acargCount = 0;
    unsafeCount = 0;
    for i = 1:numel(events)
        reasons = events(i).reasons;
        acargCount = acargCount + any(strcmp(reasons, 'ACARG requested replanning.'));
        unsafeCount = unsafeCount + any(strcmp(reasons, 'Upcoming active path is unsafe.'));
    end
end

function value = compactResult(result)
    value = struct('goalReached', result.goalReached, ...
        'collisionOccurred', result.collisionOccurred, ...
        'terminationReason', result.terminationReason, ...
        'simulationTime', result.simulationTime, ...
        'distanceTravelled', result.distanceTravelled, ...
        'maximumRisk', max([result.log.totalRisk]), ...
        'statesObserved', {unique({result.log.acargState}, 'stable')}, ...
        'stopTime', result.metrics.timeInCONSERVATIVE_STOP, ...
        'replans', result.numberOfReplans, ...
        'failedReplans', result.numberOfFailedReplans, ...
        'unsafeMovingFrames', sum(~[result.log.pathSafe] & [result.log.egoSpeed] > 0.05));
end
