function scenario = createDetectionLossScenario(cfg)
%CREATEDETECTIONLOSSSCENARIO Temporarily hide and then restore an actor.

    actor = makePhase8Actor(802, 'auto', [44 10], [0 -2.0], ...
        [3.2 1.5], 'Temporarily occluded auto');
    scenario = makePhase9Scenario('Temporary Detection Loss', 'detection-loss', ...
        'A moving auto is missed for six frames and later reappears with the same ID.', ...
        actor, [72 0 0], 23, 902, cfg);
    schedule = struct('ActorID', 802, 'StartTime', 4, 'EndTime', 5, ...
        'IsDetected', false, 'Confidence', NaN, ...
        'PositionStd', [], 'VelocityStd', []);
    scenario.detectionModifierFcn = @(d,t,varargin) ...
        applyPhase9DetectionSchedule(d, t, schedule);
    scenario.disturbanceWindow = [4 5];
    scenario.recoveryCriterion = 'detection-restored';
end
