function scenario = createConfidenceDropScenario(cfg)
%CREATECONFIDENCEDROPSCENARIO Degrade and restore one continuous detection.

    actor = makePhase8Actor(801, 'pedestrian', [42 9], [0 -2.0], ...
        [0.6 0.6], 'Confidence-drop pedestrian');
    scenario = makePhase9Scenario('Confidence Drop', 'confidence-drop', ...
        'A continuous pedestrian track receives low-confidence measurements, then recovers.', ...
        actor, [70 0 0], 22, 901, cfg);
    schedule = struct('ActorID', 801, 'StartTime', 4, 'EndTime', 7, ...
        'IsDetected', true, 'Confidence', 0.25, ...
        'PositionStd', [1.5 1.5 0.1], 'VelocityStd', [0.8 0.8 0.1]);
    scenario.detectionModifierFcn = @(d,t,varargin) ...
        applyPhase9DetectionSchedule(d, t, schedule);
    scenario.disturbanceWindow = [4 7];
    scenario.recoveryCriterion = 'confidence-restored';
end
