function scenario = createMultipleRiskScenario(cfg)
%CREATEMULTIPLERISKSCENARIO Two independent crossing conflicts.

    actors(1) = makePhase8Actor(804, 'car', [32 8], [0 -1.6], ...
        [4.7 1.8], 'Early crossing car');
    actors(2) = makePhase8Actor(805, 'pedestrian', [58 14], [0 -1.8], ...
        [0.6 0.6], 'Later crossing pedestrian');
    scenario = makePhase9Scenario('Multiple Simultaneous Risks', 'multiple-risks', ...
        'A car and pedestrian create overlapping, actor-specific crossing risks.', ...
        actors, [82 0 0], 26, 904, cfg);
    scenario.recoveryCriterion = 'goal';
end
