function explanation = explainACARGDecision(frame, cfg)
%EXPLAINACARGDECISION Convert one logged frame into numerical ACARG evidence.

    if nargin < 2, cfg = config(); end
    diagnostics = frame.acargDiagnostics;
    actor = struct([]);
    if isfield(diagnostics, 'dominantActorID') && ...
            isfinite(diagnostics.dominantActorID)
        index = find([frame.actorRiskDetails.ActorID] == ...
            diagnostics.dominantActorID, 1);
        if ~isempty(index), actor = frame.actorRiskDetails(index); end
    end
    explanation = struct('frameTime', frame.time, ...
        'totalRisk', frame.totalRisk, ...
        'dominantActorID', diagnostics.dominantActorID, ...
        'dominantActorRisk', diagnostics.dominantActorRisk, ...
        'dominantActorClass', string(diagnostics.dominantActorClass), ...
        'previousGovernorState', string(diagnostics.previousState), ...
        'finalGovernorState', string(frame.acargState), ...
        'stateChanged', diagnostics.stateChanged, ...
        'thresholdName', string(diagnostics.relevantThresholdName), ...
        'threshold', diagnostics.relevantThreshold, ...
        'thresholdCrossed', diagnostics.thresholdCrossed, ...
        'hysteresisActive', diagnostics.hysteresisActive, ...
        'reason', string(diagnostics.stateReason), ...
        'speedScale', frame.speedScale, 'safetyScale', frame.safetyScale, ...
        'replanUrgency', frame.replanUrgency, ...
        'replanRequested', frame.replanRequested, ...
        'egoSpeed', frame.egoSpeed, 'desiredSpeed', frame.desiredSpeed, ...
        'acceleration', frame.acceleration, 'actor', actor, ...
        'configuredThresholds', cfg.governor.thresholds);
end
