function scenarios = getPhase9StressScenarios(cfg)
%GETPHASE9STRESSSCENARIOS Return the eight deterministic robustness cases.

    if nargin < 1, cfg = config(); end
    scenarios = {createConfidenceDropScenario(cfg), ...
        createDetectionLossScenario(cfg), ...
        createDirectionReversalScenario(cfg), ...
        createMultipleRiskScenario(cfg), ...
        createTemporaryObstructionScenario(cfg), ...
        createReplanFailureRecoveryScenario(cfg), ...
        createConservativeStopRecoveryScenario(cfg), ...
        createRapidRiskFluctuationScenario(cfg)};
end
