function table = runCPASensitivity(cfg)
%RUNCPASENSITIVITY Compare proximity with future-interaction geometry.

    if nargin < 1, cfg = config(); end
    cfg = configurePhase8Scenario(cfg, 10, 929);
    ego = struct('Position', [0 0 0], 'Velocity', [4 0 0]);
    definitions = { ...
        struct('Name','Closer moving away','ID',911,'Position',[10 0], ...
            'Velocity',[7 0]), ...
        struct('Name','Farther collision course','ID',912,'Position',[18 6], ...
            'Velocity',[0 -4/3])};
    rows = cell(numel(definitions), 1);
    for i = 1:numel(definitions)
        item = definitions{i};
        detection = struct('ID', item.ID, 'Position', [item.Position 0], ...
            'Velocity', [item.Velocity 0], 'PerceivedClass', 'car', ...
            'TrueClass', 'car', 'PositionStd', [0.1 0.1 0.1], ...
            'VelocityStd', [0.1 0.1 0.1], 'IsDetected', true, ...
            'Confidence', 0.95);
        track = initializeTracker(detection, cfg.control.dt, cfg, 0);
        prediction = predictActor(track.CurrentState, track.CurrentCovariance, ...
            cfg.prediction.horizon, cfg.prediction.dt, ...
            struct('ProcessNoise', track.ProcessNoise));
        actor = computeActorRisk(track, prediction, ego, [], cfg);
        cpa = actor.collisionDiagnostics;
        rows{i} = struct('Geometry', string(item.Name), 'ActorID', item.ID, ...
            'PhysicalDistance', actor.distance, 'CPADistance', cpa.cpaDistance, ...
            'CPATime', cpa.cpaTime, 'IsClosing', cpa.isClosing, ...
            'DistanceRisk', actor.distanceRisk, ...
            'CollisionRisk', actor.collisionRisk, 'ActorRisk', actor.risk);
    end
    table = struct2table(vertcat(rows{:}));
end
