function table = runConfidenceSensitivity(cfg)
%RUNCONFIDENCESENSITIVITY Evaluate one geometry at fixed confidence levels.

    if nargin < 1, cfg = config(); end
    cfg = configurePhase8Scenario(cfg, 10, 919);
    confidenceInputs = [0.95; 0.80; 0.60; 0.40];
    rows = cell(numel(confidenceInputs), 1);
    ego = struct('Position', [0 0 0], 'Velocity', [4 0 0]);
    for i = 1:numel(confidenceInputs)
        confidence = confidenceInputs(i);
        measurementStd = 0.10 + 1.50 * (1 - confidence);
        detection = struct('ID', 901, 'Position', [22 6 0], ...
            'Velocity', [0 -1.2 0], 'PerceivedClass', 'pedestrian', ...
            'TrueClass', 'pedestrian', ...
            'PositionStd', [measurementStd measurementStd 0.1], ...
            'VelocityStd', [0.2 0.2 0.1], 'IsDetected', true, ...
            'Confidence', confidence);
        track = initializeTracker(detection, cfg.control.dt, cfg, 0);
        acarg = acargGovernor(track, ego, cfg, []);
        actor = acarg.risk.actorRisk;
        rows{i} = struct('DetectionConfidence', confidence, ...
            'MeasurementStd', measurementStd, ...
            'TrustScore', actor.confidence, 'Uncertainty', actor.uncertainty, ...
            'ActorRisk', actor.risk, ...
            'AdaptiveScale', actor.combinedAdaptiveScale, ...
            'GovernorState', string(acarg.state));
    end
    table = struct2table(vertcat(rows{:}));
end
