function robustness = runPhase9Robustness(cfg)
%RUNPHASE9ROBUSTNESS Execute all stress cases through the shared engine.

    if nargin < 1, cfg = config(); end
    scenarios = getPhase9StressScenarios(cfg);
    runs = repmat(struct('scenarioName','','sanity',struct(), ...
        'summary',struct(),'detail',struct()), numel(scenarios), 1);
    rows = cell(numel(scenarios), 1);
    timer = tic;
    for i = 1:numel(scenarios)
        sanity = validatePhase9Scenario(scenarios{i});
        result = runClosedLoopSimulation(scenarios{i});
        [summary, detail] = collectRobustnessMetrics(scenarios{i}, result);
        rows{i} = summary;
        runs(i) = struct('scenarioName', scenarios{i}.name, ...
            'sanity', sanity, 'summary', summary, 'detail', detail);
    end
    summaryTable = struct2table(vertcat(rows{:}));
    aggregate = struct('totalScenarios', height(summaryTable), ...
        'goalReachedCount', sum(summaryTable.GoalReached), ...
        'collisionFreeCount', sum(~summaryTable.Collision), ...
        'safeTerminationCount', sum(summaryTable.SafeTermination), ...
        'recoveredCount', sum(summaryTable.RecoveryOccurred), ...
        'unexplainedFailureCount', sum(~summaryTable.GoalReached & ...
            ~summaryTable.SafeTermination), ...
        'wallClockSeconds', toc(timer));
    robustness = struct('scenarioRuns', runs, 'summaryTable', summaryTable, ...
        'aggregate', aggregate);
end
