function report = validatePhase9Scenario(scenario)
%VALIDATEPHASE9SCENARIO Validate initial geometry and common stress schema.

    required = {'name','disturbanceType','disturbanceWindow', ...
        'recoveryCriterion','egoState','goalPose','actors','config'};
    assert(all(isfield(scenario, required)), 'Phase 9 scenario schema is incomplete.');
    assert(all(isfinite([scenario.egoState.x scenario.egoState.y ...
        scenario.egoState.yaw scenario.egoState.speed scenario.goalPose])), ...
        'Ego or goal contains NaN/Inf.');
    assert(~isempty(scenario.actors) && all(isfinite([scenario.actors.Position])) && ...
        all(isfinite([scenario.actors.Velocity])), 'Actor truth is invalid.');
    [collision, clearance] = checkCollision( ...
        scenario.egoState, scenario.actors, scenario.config);
    assert(~collision, 'Scenario begins in collision.');
    [tracks, ~] = updateActorTracks(struct([]), scenario.actors, ...
        scenario.egoState, 0, scenario.config, scenario.detectionModifierFcn);
    riskMap = updateOccupancyMap(tracks, scenario.egoState, scenario.config);
    acarg = acargGovernor(tracks, scenario.egoState, scenario.config, []);
    adaptiveMap = applyAdaptiveSafetyEnvelope(riskMap, acarg, scenario.config);
    planner = createPlanner(adaptiveMap, scenario.config);
    initialPath = planPath(planner, [scenario.egoState.x scenario.egoState.y ...
        scenario.egoState.yaw], scenario.goalPose, scenario.config);
    assert(initialPath.success, 'Initial path is not feasible: %s', initialPath.failureReason);
    report = struct('scenarioName', scenario.name, 'valid', true, ...
        'initialCollision', collision, 'initialClearance', clearance, ...
        'initialRisk', acarg.risk.totalRisk, ...
        'initialState', acarg.state, 'initialPathLength', initialPath.length);
end
